ask/ask/urls.py
from django.contrib import admin
'''
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
'''

from django.conf.urls import url
from qa import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.last_questions, name='last_questions'),
    url(r'^login/', views.login_user, name='login'),
    url(r'^signup/', views.signup_user, name='signup'),
    url(r'^question/(\d+)/', views.question_detail, name='question_detail'),
    url(r'^ask/', views.question_ask, name='ask'),
    url(r'^popular/', views.popular_questions, name='popular'),
    url(r'^new/', views.last_questions, name='new'),
]

ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class QuestionManager(models.Manager):
    def new(self):
        return self.order_by('-id')
    def popular(self):
        return self.order_by('-rating')

class Question(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(User, blank=True, null=True, \
        related_name='question_to_author', on_delete=models.SET_NULL)
    likes = models.ManyToManyField(User, related_name='question_to_likes', blank=True)
    objects = QuestionManager()

    def get_url(self):
        return reverse('question_detail', args=(self.pk,))

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.text

    def __str__(self):
        return self.text

ask/qa/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Question, Answer

class AskForm(forms.Form):
    title = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)

    def __init__(self, **kwargs):
        super(AskForm, self).__init__(**kwargs)

    def clean(self):
        pass

    def save(self):
        self.cleaned_data['author'] = self._user
        question = Question(**self.cleaned_data)
        question.save()
        return question

class AnswerForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    question = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,  **kwargs):
        super(AnswerForm, self).__init__(**kwargs)

    def clean_question(self):
        question_id = self.cleaned_data['question']
        try:
            question = Question.objects.get(id=question_id)
        except Question.DoesNotExist:
            question = None
        return question

    def clean(self):
        pass

    def save(self):
        self.cleaned_data['author'] = self._user
        return Answer.objects.create(**self.cleaned_data)

class SignupForm(forms.Form):
    username = forms.CharField(max_length=64)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, **kwargs):
        super(SignupForm, self).__init__(**kwargs)

    def clean(self):
        pass

    def save(self):
        return User.objects.create_user(**self.cleaned_data)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=64)
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, **kwargs):
        super(LoginForm, self).__init__(**kwargs)

    def clean(self):
        pass

    def save(self):
        pass

ask/qa/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage
from django.views.decorators.http import require_GET
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login

from .models import Question
from .forms import AskForm, AnswerForm, SignupForm, LoginForm

@require_GET
def test(request, *args, **kwargs):
    return HttpResponse('OK')

@require_GET
@login_required
def last_questions(request):
    query_set = Question.objects.new()
    return paginate(request, query_set, 'new', 'sorted_questions.html')

@require_GET
@login_required
def popular_questions(request):
    query_set = Question.objects.popular()
    return paginate(request, query_set, 'popular', 'sorted_questions.html')

def paginate(request, query_set, reverse_url_name, template_name):
    try:
        page = int(request.GET.get('page', 1))
    except:
        page = 1
    try: 
        limit = int(request.GET.get('limit', 10))
    except:
        limit = 10
    if limit > 10:
        limit = 10
    paginator = Paginator(query_set, limit)
    paginator.baseurl = reverse(reverse_url_name)+'?page='
    try:
        page = paginator.page(page)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    return render(request, template_name, {
        'questions': page.object_list,
        'paginator': paginator,
        'page': page 
    })

@login_required
def question_detail(request, id):
    question = get_object_or_404(Question, pk=id)
    if request.method == 'POST':
        form = AnswerForm(data=request.POST)
        form._user = request.user
        if form.is_valid():
            answer = form.save()
            return HttpResponseRedirect(request.path)
    else:
        form = AnswerForm(initial={'question': question.id})
    return render(request, 'question_detail.html', {
        'question': question, 'form': form
    })

@login_required
def question_ask(request):
    if request.method == 'POST':
        form = AskForm(data=request.POST)
        form._user = request.user
        if form.is_valid():
            question = form.save()
            url = question.get_url()
            return HttpResponseRedirect(url)
    else:
        form = AskForm()
    return render(request, 'question_ask.html', {
        'form': form
        })
    
def signup_user(request):
    if request.method == 'POST':
        form = SignupForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            authenticate(user)
            login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = SignupForm()
    return render(request, 'signup_form.html', {
        'form': form
        })

def login_user(request):
    error = ''
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                error = 'Invalid login or password!'
    else:
        form = LoginForm()
    return render(request, 'login_form.html', {
        'form': form, 
        'error': error
        })

ask/qa/templates/login_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <form method="post" action="/login/">
            {% csrf_token %}
            {{ form.as_p }}
            {% if error %}
            <p style="color: red;">{{ error }}<p>
            {% endif %}    
            <input type="submit" value="Log in">
        </form>
    </body>
</html>

ask/qa/templates/question.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        {{ question.title }}<br>
        {{ question.text }}<br><br>
        {% for answer in question.answer_set.all %}
        {{ answer }}<br>
        {% endfor %}
        <form method="post" action="/question/{{ question.pk }}/">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    </body>
</html>

ask/qa/templates/question_add.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <form method="post" action="/ask/">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    </body>
</html>

ask/qa/templates/question_ask.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <form method="post" action="/ask/">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    </body>
</html>

ask/qa/templates/question_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        Title: {{ question.title }}<br>
        Text: {{ question.text }}<br>
        Author: {{ question.author }}<br><br>
        {% for answer in question.answer_set.all %}
        Answer: {{ answer.text }}<br>
        Author: {{ answer.author }}<br><br>
        {% endfor %}
        <form method="post" action="/question/{{ question.pk }}/">
            {% csrf_token %}
            <p>Answer: </p>
            <p>{{ form.text }}</p>
            <p>{{ form.question }}</p>
            <input type="submit" value="Send answer">
        </form>
    </body>
</html>

ask/qa/templates/signup_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <form method="post" action="/signup/">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign up">
        </form>
    </body>
</html>

ask/qa/templates/sorted_questions.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <ul>
            {% for question in questions %}
            <li><a href="{{ question.get_url }}">{{ question.title }}</a></li>
            {% endfor %}
        </ul>
        {% for p in paginator.page_range %}
        <a href=" {{ paginator.baseurl }}{{ p }}">{{ p }}</a>
        {% endfor %}
    </body>
</html>